services:
- docker

install: docker build -t "shawnzhu/prestodb:$TRAVIS_BRANCH" .

before_script:
  curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 &&
  chmod +x container-structure-test-linux-amd64 &&
  mkdir -p $HOME/bin &&
  export PATH=$PATH:$HOME/bin &&
  mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test

script: container-structure-test test --image shawnzhu/prestodb:$TRAVIS_BRANCH --config test_config.yaml
