schemaVersion: "2.0.0"
commandTests:
- name: jre
  command: java
  args: ["-version"]
  expectedError:
  - "1.8.0_181"
- name: python2.7
  command: python
  args: ["--version"]
  expectedError:
  - "Python\\s2.7.*"
- name: "ls /home/presto/etc"
  command: ls
  args: ["/home/presto/etc"]
  expectedOutput:
  - catalog
  - config.properties
  - jvm.config
  - node.properties
fileExistenceTests:
- name: presto-server
  path: /home/presto/bin/launcher
- name: presto-home
  path: /home/presto
- name: presto-connector-db2
  path: /home/presto/plugin/db2
metadataTest:
  env:
  - key: PRESTO_VERSION
    value: 0.193
  - key: PRESTO_HOME
    value: /home/presto
  labels:
  - key: "MAINTAINER"
    value: "shawnzhu@users.noreply.github.com"
  exposedPorts: ["8080"]
  volumes: ["/home/presto/etc", "/home/presto/data"]
  workdir: "/home/presto"
