schemaVersion: "2.0.0"
fileExistenceTests:
- name: presto-home
  path: /usr/lib/presto
  uid: 1000
  gid: 1000
- name: presto-connector-db2
  path: /usr/lib/presto/plugin/db2
  uid: 1000
  gid: 1000
- name: presto-db2.jar
  path: /usr/lib/presto/plugin/db2/presto-db2-340.jar
metadataTest:
  env:
  - key: JAVA_HOME
    value: /usr/lib/jvm/java-11
  exposedPorts: ["8080"]
